# Generated by Django 3.0.6 on 2020-07-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200707_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='details',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
    ]
