# Generated by Django 3.0.6 on 2020-07-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_todo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
